name: Weekly Python Job

on:
  schedule:
    # 每周五16:00（北京时间），对应UTC时间8:00
    - cron: '0 8 * * 5'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如有依赖

    - name: Execute Python script
      run: python data_capture_weekly_1.py  # 替换为你的脚本路径

